<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MessageExchanger.Shared\MessageExchanger.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ProtocolSI">
      <HintPath>..\MessageExchanger.Shared\ProtocolSI\ProtocolSI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
